apiVersion: v1
kind: Namespace
metadata:
  name: wordpress-blog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-blog
  namespace: wordpress-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-blog
  template:
    metadata:
      labels:
        app: wordpress-blog
    spec:
      containers:
      - name: wordpress-blog
        image: chris2274/myblog:latest
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_HOST
          value: "mysqlchris2274.mysql.database.azure.com"
        - name: DATABASE_USERNAME
          value: "chris"
        - name: DATABASE_PASSWORD
          value: "P@ssw0rd!"
        - name: DATABASE_NAME
          value: "flexibleserverdb"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - wordpress-blog
              topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: php-svc
  namespace: wordpress-blog
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: wordpress-blog
    #q